/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LookUp;

import Dao.ProdukDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static koneksi.Koneksi.getConnection;

/**
 *
 * @author Daffa
 */
public class RequestStock extends javax.swing.JDialog {

    Connection kon;
    ProdukDao dao = new ProdukDao();
    
    public RequestStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tampilkanDataTransaksi();
    }
    
    private void tampilkanDataTransaksi() {
        DefaultTableModel model = dao.getPendingTransactions();
        tblReq.setModel(model);
        tblReq.getColumnModel().getColumn(3).setMinWidth(0);
        tblReq.getColumnModel().getColumn(3).setMaxWidth(0);
        tblReq.getColumnModel().getColumn(3).setWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReq = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReq);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Permintaan Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReqMouseClicked
        kon = getConnection();
        int row = tblReq.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih permintaan restock yang ingin diterima!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idTransaksi = tblReq.getValueAt(row, 0).toString();
        int jumlah = Integer.parseInt(tblReq.getValueAt(row, 3).toString());

        String inputJumlah = JOptionPane.showInputDialog(this, "Masukkan jumlah stok yang ingin diRestock:", jumlah);
        if (inputJumlah == null || inputJumlah.trim().isEmpty()) {
            return;
        }

        int jumlahRestock = Integer.parseInt(inputJumlah);

        try {
            String sql = "UPDATE transaksi_suplier SET status = 'accepted', jumlah = ? WHERE idTrsuplier = ?";
            PreparedStatement ps = kon.prepareStatement(sql);
            ps.setInt(1, jumlahRestock);
            ps.setString(2, idTransaksi);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Permintaan restock berhasil dikirim ke Suplier!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            tampilkanDataTransaksi();
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengirim permintaan restock: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_tblReqMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RequestStock dialog = new RequestStock(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReq;
    // End of variables declaration//GEN-END:variables
}
