/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Daffa
 */
public class MenutView extends javax.swing.JFrame {
    
    private String username;
    private String kelas;

    int xx, xy;
    public MenutView(String username, String kelas) {
        initComponents();
        this.username = username;
        lblWelcome.setText("Welcome "+ username);
        this.kelas = kelas;
        lblKelas.setText(kelas);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        lb_HeaderUP = new javax.swing.JLabel();
        lb_MasterData = new javax.swing.JLabel();
        lb_Transaksi = new javax.swing.JLabel();
        lb_Laporan = new javax.swing.JLabel();
        pn_DashboardMain = new javax.swing.JPanel();
        pn_DashboardLine = new javax.swing.JPanel();
        lb_iconDashboard = new javax.swing.JLabel();
        btn_Dashboard = new javax.swing.JLabel();
        pn_ProductMain = new javax.swing.JPanel();
        pn_ProductLine = new javax.swing.JPanel();
        lb_iconProduct = new javax.swing.JLabel();
        btn_Product = new javax.swing.JLabel();
        pn_TrPelangganMain = new javax.swing.JPanel();
        pn_TrPelangganLine = new javax.swing.JPanel();
        lb_iconTrPelanggan = new javax.swing.JLabel();
        btn_TrPelanggan = new javax.swing.JLabel();
        pn_TrSuplierMain = new javax.swing.JPanel();
        pn_TrSuplierLine = new javax.swing.JPanel();
        lb_iconTrSuplier = new javax.swing.JLabel();
        btn_TrSuplier = new javax.swing.JLabel();
        pn_LpKeuanganMain = new javax.swing.JPanel();
        pn_LpKeuanganLine = new javax.swing.JPanel();
        lb_iconLpKeuangan = new javax.swing.JLabel();
        btn_LpKeuangan = new javax.swing.JLabel();
        pn_LpTransaksiMain = new javax.swing.JPanel();
        pn_LpTransaksiLine = new javax.swing.JPanel();
        lb_iconLpTransaksi = new javax.swing.JLabel();
        btn_LpTransaksi = new javax.swing.JLabel();
        pn_kanan = new java.awt.Panel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jPanelGradient1 = new pallet.JPanelGradient();
        lblWelcome = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        lblKelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 636));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo_rpl_75px.png"))); // NOI18N

        lb_HeaderUP.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lb_HeaderUP.setText("Unit Produksi RPL");

        lb_MasterData.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_MasterData.setForeground(new java.awt.Color(153, 153, 153));
        lb_MasterData.setText("Master Data");

        lb_Transaksi.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_Transaksi.setForeground(new java.awt.Color(153, 153, 153));
        lb_Transaksi.setText("Laporan");

        lb_Laporan.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_Laporan.setForeground(new java.awt.Color(153, 153, 153));
        lb_Laporan.setText("Transaksi");

        pn_DashboardMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_DashboardMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_DashboardMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_DashboardMainMouseExited(evt);
            }
        });

        pn_DashboardLine.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pn_DashboardLineLayout = new javax.swing.GroupLayout(pn_DashboardLine);
        pn_DashboardLine.setLayout(pn_DashboardLineLayout);
        pn_DashboardLineLayout.setHorizontalGroup(
            pn_DashboardLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_DashboardLineLayout.setVerticalGroup(
            pn_DashboardLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_iconDashboard.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_iconDashboard.setForeground(new java.awt.Color(153, 153, 153));
        lb_iconDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icDashboard.png"))); // NOI18N

        btn_Dashboard.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Dashboard.setForeground(new java.awt.Color(51, 51, 51));
        btn_Dashboard.setText("Dashboard");

        javax.swing.GroupLayout pn_DashboardMainLayout = new javax.swing.GroupLayout(pn_DashboardMain);
        pn_DashboardMain.setLayout(pn_DashboardMainLayout);
        pn_DashboardMainLayout.setHorizontalGroup(
            pn_DashboardMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DashboardMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_DashboardLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iconDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_DashboardMainLayout.setVerticalGroup(
            pn_DashboardMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DashboardMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_DashboardLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(pn_DashboardMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_DashboardMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_iconDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_DashboardMainLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_Dashboard)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pn_ProductMain.setPreferredSize(new java.awt.Dimension(228, 60));
        pn_ProductMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_ProductMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_ProductMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_ProductMainMouseExited(evt);
            }
        });

        pn_ProductLine.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pn_ProductLineLayout = new javax.swing.GroupLayout(pn_ProductLine);
        pn_ProductLine.setLayout(pn_ProductLineLayout);
        pn_ProductLineLayout.setHorizontalGroup(
            pn_ProductLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_ProductLineLayout.setVerticalGroup(
            pn_ProductLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_iconProduct.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_iconProduct.setForeground(new java.awt.Color(153, 153, 153));
        lb_iconProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icProduct-transformed.png"))); // NOI18N

        btn_Product.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_Product.setForeground(new java.awt.Color(51, 51, 51));
        btn_Product.setText("Product");

        javax.swing.GroupLayout pn_ProductMainLayout = new javax.swing.GroupLayout(pn_ProductMain);
        pn_ProductMain.setLayout(pn_ProductMainLayout);
        pn_ProductMainLayout.setHorizontalGroup(
            pn_ProductMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ProductMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_ProductLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iconProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Product)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_ProductMainLayout.setVerticalGroup(
            pn_ProductMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ProductMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_ProductLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(pn_ProductMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_ProductMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_Product)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pn_TrPelangganMain.setPreferredSize(new java.awt.Dimension(228, 60));
        pn_TrPelangganMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_TrPelangganMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TrPelangganMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TrPelangganMainMouseExited(evt);
            }
        });

        pn_TrPelangganLine.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pn_TrPelangganLineLayout = new javax.swing.GroupLayout(pn_TrPelangganLine);
        pn_TrPelangganLine.setLayout(pn_TrPelangganLineLayout);
        pn_TrPelangganLineLayout.setHorizontalGroup(
            pn_TrPelangganLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_TrPelangganLineLayout.setVerticalGroup(
            pn_TrPelangganLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_iconTrPelanggan.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_iconTrPelanggan.setForeground(new java.awt.Color(153, 153, 153));
        lb_iconTrPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/transaksiPlgn.png"))); // NOI18N

        btn_TrPelanggan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_TrPelanggan.setForeground(new java.awt.Color(51, 51, 51));
        btn_TrPelanggan.setText("Transaksi Pelanggan");

        javax.swing.GroupLayout pn_TrPelangganMainLayout = new javax.swing.GroupLayout(pn_TrPelangganMain);
        pn_TrPelangganMain.setLayout(pn_TrPelangganMainLayout);
        pn_TrPelangganMainLayout.setHorizontalGroup(
            pn_TrPelangganMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TrPelangganMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_TrPelangganLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iconTrPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TrPelanggan)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pn_TrPelangganMainLayout.setVerticalGroup(
            pn_TrPelangganMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TrPelangganMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_TrPelangganLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(pn_TrPelangganMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconTrPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_TrPelangganMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_TrPelanggan)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pn_TrSuplierMain.setPreferredSize(new java.awt.Dimension(228, 60));
        pn_TrSuplierMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_TrSuplierMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TrSuplierMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TrSuplierMainMouseExited(evt);
            }
        });

        pn_TrSuplierLine.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pn_TrSuplierLineLayout = new javax.swing.GroupLayout(pn_TrSuplierLine);
        pn_TrSuplierLine.setLayout(pn_TrSuplierLineLayout);
        pn_TrSuplierLineLayout.setHorizontalGroup(
            pn_TrSuplierLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_TrSuplierLineLayout.setVerticalGroup(
            pn_TrSuplierLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_iconTrSuplier.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_iconTrSuplier.setForeground(new java.awt.Color(153, 153, 153));
        lb_iconTrSuplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/trSup.png"))); // NOI18N

        btn_TrSuplier.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_TrSuplier.setForeground(new java.awt.Color(51, 51, 51));
        btn_TrSuplier.setText("Transaksi Supplier");

        javax.swing.GroupLayout pn_TrSuplierMainLayout = new javax.swing.GroupLayout(pn_TrSuplierMain);
        pn_TrSuplierMain.setLayout(pn_TrSuplierMainLayout);
        pn_TrSuplierMainLayout.setHorizontalGroup(
            pn_TrSuplierMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TrSuplierMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_TrSuplierLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iconTrSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TrSuplier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_TrSuplierMainLayout.setVerticalGroup(
            pn_TrSuplierMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TrSuplierMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_TrSuplierLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(pn_TrSuplierMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconTrSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_TrSuplierMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_TrSuplier)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pn_LpKeuanganMain.setPreferredSize(new java.awt.Dimension(228, 60));
        pn_LpKeuanganMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LpKeuanganMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_LpKeuanganMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_LpKeuanganMainMouseExited(evt);
            }
        });

        pn_LpKeuanganLine.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pn_LpKeuanganLineLayout = new javax.swing.GroupLayout(pn_LpKeuanganLine);
        pn_LpKeuanganLine.setLayout(pn_LpKeuanganLineLayout);
        pn_LpKeuanganLineLayout.setHorizontalGroup(
            pn_LpKeuanganLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_LpKeuanganLineLayout.setVerticalGroup(
            pn_LpKeuanganLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_iconLpKeuangan.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_iconLpKeuangan.setForeground(new java.awt.Color(153, 153, 153));
        lb_iconLpKeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/payments.png"))); // NOI18N

        btn_LpKeuangan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_LpKeuangan.setForeground(new java.awt.Color(51, 51, 51));
        btn_LpKeuangan.setText("Laporan Keuangan");

        javax.swing.GroupLayout pn_LpKeuanganMainLayout = new javax.swing.GroupLayout(pn_LpKeuanganMain);
        pn_LpKeuanganMain.setLayout(pn_LpKeuanganMainLayout);
        pn_LpKeuanganMainLayout.setHorizontalGroup(
            pn_LpKeuanganMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LpKeuanganMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_LpKeuanganLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iconLpKeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_LpKeuangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_LpKeuanganMainLayout.setVerticalGroup(
            pn_LpKeuanganMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LpKeuanganMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_LpKeuanganLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(pn_LpKeuanganMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconLpKeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_LpKeuanganMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_LpKeuangan)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pn_LpTransaksiMain.setPreferredSize(new java.awt.Dimension(228, 60));
        pn_LpTransaksiMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LpTransaksiMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_LpTransaksiMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_LpTransaksiMainMouseExited(evt);
            }
        });

        pn_LpTransaksiLine.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pn_LpTransaksiLineLayout = new javax.swing.GroupLayout(pn_LpTransaksiLine);
        pn_LpTransaksiLine.setLayout(pn_LpTransaksiLineLayout);
        pn_LpTransaksiLineLayout.setHorizontalGroup(
            pn_LpTransaksiLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_LpTransaksiLineLayout.setVerticalGroup(
            pn_LpTransaksiLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_iconLpTransaksi.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        lb_iconLpTransaksi.setForeground(new java.awt.Color(153, 153, 153));
        lb_iconLpTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/history.png"))); // NOI18N

        btn_LpTransaksi.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_LpTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        btn_LpTransaksi.setText("Laporan Transaksi");

        javax.swing.GroupLayout pn_LpTransaksiMainLayout = new javax.swing.GroupLayout(pn_LpTransaksiMain);
        pn_LpTransaksiMain.setLayout(pn_LpTransaksiMainLayout);
        pn_LpTransaksiMainLayout.setHorizontalGroup(
            pn_LpTransaksiMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LpTransaksiMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_LpTransaksiLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_iconLpTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_LpTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_LpTransaksiMainLayout.setVerticalGroup(
            pn_LpTransaksiMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LpTransaksiMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pn_LpTransaksiLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(pn_LpTransaksiMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconLpTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_LpTransaksiMainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_LpTransaksi)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Transaksi)
                            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lb_MasterData)
                                .addComponent(pn_DashboardMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_ProductMain, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(pn_TrPelangganMain, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(pn_TrSuplierMain, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(lb_Laporan))
                            .addComponent(pn_LpKeuanganMain, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(pn_LpTransaksiMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_HeaderUP)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lb_HeaderUP)))
                .addGap(35, 35, 35)
                .addComponent(lb_MasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pn_DashboardMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pn_ProductMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lb_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pn_TrPelangganMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pn_TrSuplierMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lb_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pn_LpKeuanganMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pn_LpTransaksiMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setMaximumSize(new java.awt.Dimension(1038, 621));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jPanelGradient1.setColorEnd(new java.awt.Color(51, 255, 255));
        jPanelGradient1.setColorStart(new java.awt.Color(0, 0, 255));

        lblWelcome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome,User");

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        Logout.setContentAreaFilled(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        lblKelas.setText("jLabel2");

        javax.swing.GroupLayout jPanelGradient1Layout = new javax.swing.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome)
                    .addComponent(lblKelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 811, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logout)
                    .addGroup(jPanelGradient1Layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKelas)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addComponent(jPanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void pn_DashboardMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMainMouseClicked
        pn_DashboardMain.setBackground(new Color(240, 240, 240));
        pn_DashboardLine.setBackground(new Color(255, 255, 255));

        pn_utama.removeAll();
        pn_utama.add(new MenuDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_DashboardMainMouseClicked

    private void pn_DashboardMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMainMouseEntered
        pn_DashboardMain.setBackground(new Color(255, 255, 255));
        pn_DashboardLine.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_pn_DashboardMainMouseEntered

    private void pn_DashboardMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMainMouseExited
        pn_DashboardMain.setBackground(new Color(240, 240, 240));
        pn_DashboardLine.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_pn_DashboardMainMouseExited

    private void pn_ProductMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_ProductMainMouseClicked
        pn_ProductMain.setBackground(new Color(240, 240, 240));
        pn_ProductLine.setBackground(new Color(255, 255, 255));

        pn_utama.removeAll();
        pn_utama.add(new MenuProduk());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_ProductMainMouseClicked

    private void pn_ProductMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_ProductMainMouseEntered
        pn_ProductMain.setBackground(new Color(255, 255, 255));
        pn_ProductLine.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_pn_ProductMainMouseEntered

    private void pn_ProductMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_ProductMainMouseExited
        pn_ProductMain.setBackground(new Color(240, 240, 240));
        pn_ProductLine.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_pn_ProductMainMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
    
        if (confirm == JOptionPane.YES_OPTION) {
            // Menutup frame utama yang berisi panel ini
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void pn_TrPelangganMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrPelangganMainMouseClicked
        pn_TrPelangganMain.setBackground(new Color(240, 240, 240));
        pn_TrPelangganLine.setBackground(new Color(255, 255, 255));

        pn_utama.removeAll();
        pn_utama.add(new MenuTransaksiPemesanan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_TrPelangganMainMouseClicked

    private void pn_TrPelangganMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrPelangganMainMouseEntered
        pn_TrPelangganMain.setBackground(new Color(255, 255, 255));
        pn_TrPelangganLine.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_pn_TrPelangganMainMouseEntered

    private void pn_TrPelangganMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrPelangganMainMouseExited
        pn_TrPelangganMain.setBackground(new Color(240, 240, 240));
        pn_TrPelangganLine.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_pn_TrPelangganMainMouseExited

    private void pn_TrSuplierMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrSuplierMainMouseClicked
        pn_TrSuplierMain.setBackground(new Color(240, 240, 240));
        pn_TrSuplierLine.setBackground(new Color(255, 255, 255));

        pn_utama.removeAll();
        pn_utama.add(new MenuTransaksiSuplier());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_TrSuplierMainMouseClicked

    private void pn_TrSuplierMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrSuplierMainMouseEntered
        pn_TrSuplierMain.setBackground(new Color(255, 255, 255));
        pn_TrSuplierLine.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_pn_TrSuplierMainMouseEntered

    private void pn_TrSuplierMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrSuplierMainMouseExited
        pn_TrSuplierMain.setBackground(new Color(240, 240, 240));
        pn_TrSuplierLine.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_pn_TrSuplierMainMouseExited

    private void pn_LpKeuanganMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpKeuanganMainMouseClicked
        pn_LpKeuanganMain.setBackground(new Color(240, 240, 240));
        pn_LpKeuanganLine.setBackground(new Color(255, 255, 255));

        pn_utama.removeAll();
        pn_utama.add(new MenuLaporanKeuangan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_LpKeuanganMainMouseClicked

    private void pn_LpKeuanganMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpKeuanganMainMouseEntered
        pn_LpKeuanganMain.setBackground(new Color(255, 255, 255));
        pn_LpKeuanganLine.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_pn_LpKeuanganMainMouseEntered

    private void pn_LpKeuanganMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpKeuanganMainMouseExited
        pn_LpKeuanganMain.setBackground(new Color(240, 240, 240));
        pn_LpKeuanganLine.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_pn_LpKeuanganMainMouseExited

    private void pn_LpTransaksiMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpTransaksiMainMouseClicked
        pn_LpTransaksiMain.setBackground(new Color(240, 240, 240));
        pn_LpTransaksiLine.setBackground(new Color(255, 255, 255));

        pn_utama.removeAll();
        pn_utama.add(new MenuLaporanTransaksi());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_LpTransaksiMainMouseClicked

    private void pn_LpTransaksiMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpTransaksiMainMouseEntered
        pn_LpTransaksiMain.setBackground(new Color(255, 255, 255));
        pn_LpTransaksiLine.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_pn_LpTransaksiMainMouseEntered

    private void pn_LpTransaksiMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LpTransaksiMainMouseExited
        pn_LpTransaksiMain.setBackground(new Color(240, 240, 240));
        pn_LpTransaksiLine.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_pn_LpTransaksiMainMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenutView().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JLabel btn_Dashboard;
    private javax.swing.JLabel btn_LpKeuangan;
    private javax.swing.JLabel btn_LpTransaksi;
    private javax.swing.JLabel btn_Product;
    private javax.swing.JLabel btn_TrPelanggan;
    private javax.swing.JLabel btn_TrSuplier;
    private javax.swing.JLabel jLabel1;
    private pallet.JPanelGradient jPanelGradient1;
    private javax.swing.JLabel lb_HeaderUP;
    private javax.swing.JLabel lb_Laporan;
    private javax.swing.JLabel lb_MasterData;
    private javax.swing.JLabel lb_Transaksi;
    private javax.swing.JLabel lb_iconDashboard;
    private javax.swing.JLabel lb_iconLpKeuangan;
    private javax.swing.JLabel lb_iconLpTransaksi;
    private javax.swing.JLabel lb_iconProduct;
    private javax.swing.JLabel lb_iconTrPelanggan;
    private javax.swing.JLabel lb_iconTrSuplier;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pn_DashboardLine;
    private javax.swing.JPanel pn_DashboardMain;
    private javax.swing.JPanel pn_LpKeuanganLine;
    private javax.swing.JPanel pn_LpKeuanganMain;
    private javax.swing.JPanel pn_LpTransaksiLine;
    private javax.swing.JPanel pn_LpTransaksiMain;
    private javax.swing.JPanel pn_ProductLine;
    private javax.swing.JPanel pn_ProductMain;
    private javax.swing.JPanel pn_TrPelangganLine;
    private javax.swing.JPanel pn_TrPelangganMain;
    private javax.swing.JPanel pn_TrSuplierLine;
    private javax.swing.JPanel pn_TrSuplierMain;
    private javax.swing.JPanel pn_dasar;
    private java.awt.Panel pn_kanan;
    private java.awt.Panel pn_kiri;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
