/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.TransaksiSuplierDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static koneksi.Koneksi.getConnection;
import model.Transaksi_suplier;

/**
 *
 * @author Hp
 */
public class MenuTransaksiSuplier extends javax.swing.JPanel {

    TransaksiSuplierDao dao = new TransaksiSuplierDao();
    Connection kon;
    
    public MenuTransaksiSuplier() {
        initComponents();
        tampilkanDataTransaksi();
    }     

    private void tampilkanDataTransaksi() {
        DefaultTableModel model = dao.tampilkanTransaksiAccepted();
        tblSup.setModel(model);
        tblSup.getColumnModel().getColumn(4).setMinWidth(0);
        tblSup.getColumnModel().getColumn(4).setMaxWidth(0);
        tblSup.getColumnModel().getColumn(4).setWidth(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1038, 621));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Transaksi Supplier");

        tblSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produk", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupMouseClicked
        kon = getConnection();
        int row = tblSup.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih permintaan restock yang ingin diselesaikan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idTransaksi = tblSup.getValueAt(row, 0).toString();
        String namaSuplierLama = tblSup.getValueAt(row, 4).toString(); // Ambil nama suplier dari tabel

        // Input untuk mengubah nama suplier
        String namaSuplierBaru = JOptionPane.showInputDialog(this, "Masukkan nama suplier baru:", namaSuplierLama);
        if (namaSuplierBaru == null || namaSuplierBaru.trim().isEmpty()) {
            return;
        }

        try {
            String sql = "UPDATE transaksi_suplier SET status = 'completed', nmSuplier = ? WHERE idTrsuplier = ?";
            PreparedStatement ps = kon.prepareStatement(sql);
            ps.setString(1, namaSuplierBaru);
            ps.setString(2, idTransaksi);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Permintaan restock berhasil diselesaikan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            tampilkanDataTransaksi();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyelesaikan permintaan restock: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblSupMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSup;
    // End of variables declaration//GEN-END:variables
}
